image: node:18-alpine

default:
  tags:
    - docker

stages: # List of stages for jobs, and their order of execution
  - test
  - deploy

test-job:
  stage: test
  script:
    - echo "Linting code..."
    - npm clean-install
    - npx next telemetry disable
    - npx next telemetry status
    - npm run format:check
    - echo "No formatting issues found."
    - npm run lint
    - echo "No lint issues found."
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
